### ISSUE TITLE
`--leaf` option to disable recursive removal

### ISSUE THREAD

**Issue by Dimava** [line/ts-remove-unused#42]
I have stuff that depends on stuff that depends on stuff, and if when I run this script it can easily delete half of my codebase because I've missed some `--skip` flag

Please add `--leaf` flag so it can show me what things are unused so I can commit them, or revert and add some new `--skip`s, and then proceed removing further

**Comment by kazushisan** [comment]
Can you elaborate a bit more about what you expect leaf to output?

**Comment by Dimava** [comment]
> Can you elaborate a bit more about what you expect leaf to output?
Maybe a better name is `--no-recursive-deletion`

```ts
// a.ts
export function a() {}
```
```ts
// b.ts
import { a } from './a'
a()
```
```ts
// main.ts
```
FIle `b.ts` in unused, so it's removed.
Then file `a.ts` is also unused, but since it was used before the deletion of `b.ts` it's untouched

If you rerun the script, `a.ts` will be now deleted as there's no `b.ts` that uses it

**Comment by kazushisan** [comment]
Actually, the current implementation does not recursively execute, it just goes through the list of files parsed by typescript compiler once. Since the process will load the latest state before processing a file, it may look like it’s recursively running.

You can check this behavior by changing the file names of your example; in some cases your issue should not reproduce.

my feeling is that this behavior is acceptable although not the best and changing the behavior to your needs requires too much complexity.


I think that your issue should be mitigated if the CLI is faster, what do you think?

**Comment by kazushisan** [comment]
Due to the optimizations I've made, `--leaf` as described is the default behavior since 0.7.0 so I will close this issue!
